[package]
name = "justix"
version = "0.1.0"
authors = ["Justin Alan Ryan <justin.alan.ryan@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-justix.json"

[dependencies]
bootloader = "0.3.4"
